### ISSUE TITLE
Throttle.java: Do not hardcode the number of semaphores

### ISSUE THREAD

**Issue by mkoncek** [mizdebsk/mbici-workflow#3]
It may be a good idea to replace numeric constants used for the number of semaphores with some number derived from the number of available CPU cores / threads.

**Comment by mizdebsk** [comment]
What values would you propose?

**Comment by mkoncek** [comment]
My idea was that instead of hardcoding constant number of semaphores, you would only hardcode multipliers (of available threads/cores).
For example if you know that 32 concurrent tasks work well on a system with 16 threads, you would simply hardcode a multiplier of 2.
Then you wouldn't have to change your source when someone, some time later, uses this tool with 64 available threads.
Simply put: make the tool scalable with a system with an infinite amount of cores.

**Comment by mizdebsk** [comment]
I get the idea. But what exact values would you propose?
Assuming `n` is the number of processors online, what should be the value of `maxCheckoutTasks`, `maxSrpmTasks` and `maxRpmTasks`?

**Comment by mkoncek** [comment]
1) From my personal experience: checkout is limited by network and disk, I think it is fine to keep the number hardcoded.
2) For Srpm and Rpm tasks I would say something around 3/2× up to 2× of the available CPU threads.

**Comment by mkoncek** [comment]
Commits 9a3d6f6ac8cdda505953230c27f7696537a11bbe and d10ba982447672d47c6873a055488f63c85b1abf addressed this.
